#!/bin/bash
# =============================================================================
# Learn AI — Data Engineering Track Setup
# =============================================================================
# One-command setup for the DE track. Run from your capstone repo root.
#
# What it does:
#   1. Creates a Python virtual environment
#   2. Installs dependencies
#   3. Prompts for environment variables (GCP project, API keys)
#   4. Writes a .env file
#   5. Runs the Session 0 preflight check
#
# Usage:
#   bash setup.sh
#
# Safe to re-run — skips steps that are already done.
# =============================================================================

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BOLD}Learn AI — Data Engineering Track Setup${NC}"
echo "=============================================="
echo ""

# ---- Step 1: Python virtual environment ----
echo -e "${BOLD}[1/5] Python virtual environment${NC}"
if [ -d "venv" ] || [ -d ".venv" ]; then
  VENV_DIR=$([ -d "venv" ] && echo "venv" || echo ".venv")
  echo -e "  ${GREEN}EXISTS${NC}  Virtual environment found at ${VENV_DIR}/"
else
  if command -v python3 &> /dev/null; then
    python3 -m venv venv
    VENV_DIR="venv"
    echo -e "  ${GREEN}CREATED${NC}  Virtual environment at venv/"
  else
    echo -e "  ${RED}FAIL${NC}  python3 not found. Install Python 3.9+ first."
    exit 1
  fi
fi

# Activate it
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
echo "  Activated: $(python3 --version)"

# ---- Step 2: Install dependencies ----
echo ""
echo -e "${BOLD}[2/5] Install dependencies${NC}"
if [ -f "requirements.txt" ]; then
  pip install -q -r requirements.txt
  echo -e "  ${GREEN}DONE${NC}  Installed from requirements.txt"
else
  # Install common DE track dependencies
  pip install -q requests pandas pytest anthropic
  echo -e "  ${GREEN}DONE${NC}  Installed defaults: requests, pandas, pytest, anthropic"

  # Create a requirements.txt for them
  pip freeze > requirements.txt
  echo "  Created requirements.txt"
fi

# ---- Step 3: Environment variables ----
echo ""
echo -e "${BOLD}[3/5] Environment variables${NC}"

if [ -f ".env" ]; then
  echo -e "  ${GREEN}EXISTS${NC}  .env file found — loading it"
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
else
  echo "  No .env file found. Let's create one."
  echo ""

  # GCP Project ID
  CURRENT_PROJECT=""
  if command -v gcloud &> /dev/null; then
    CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)
  fi

  if [ -n "$CURRENT_PROJECT" ] && [ "$CURRENT_PROJECT" != "(unset)" ]; then
    read -rp "  GCP Project ID [$CURRENT_PROJECT]: " GCP_PROJECT_ID
    GCP_PROJECT_ID=${GCP_PROJECT_ID:-$CURRENT_PROJECT}
  else
    read -rp "  GCP Project ID: " GCP_PROJECT_ID
  fi

  # GCP Region
  read -rp "  GCP Region [us-central1]: " GCP_REGION
  GCP_REGION=${GCP_REGION:-us-central1}

  # Anthropic API Key
  echo ""
  echo "  Anthropic API key is optional now (needed for Session 4+)."
  echo "  Get one at: https://console.anthropic.com"
  read -rp "  Anthropic API Key (press Enter to skip): " ANTHROPIC_API_KEY

  # Write .env
  cat > .env << ENVFILE
# Learn AI — Data Engineering Track
# Generated by setup.sh on $(date +%Y-%m-%d)

GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_REGION=${GCP_REGION}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENVFILE

  echo ""
  echo -e "  ${GREEN}CREATED${NC}  .env file written"

  # Export for current session
  export GCP_PROJECT_ID GCP_REGION ANTHROPIC_API_KEY
fi

# ---- Step 4: Ensure .env is gitignored ----
echo ""
echo -e "${BOLD}[4/5] Git safety${NC}"
if [ -f ".gitignore" ]; then
  if grep -q "^\.env$" .gitignore 2>/dev/null; then
    echo -e "  ${GREEN}OK${NC}  .env is in .gitignore"
  else
    echo ".env" >> .gitignore
    echo -e "  ${GREEN}ADDED${NC}  .env to .gitignore"
  fi
else
  echo -e ".env\nvenv/\n__pycache__/\n*.pyc\n.terraform/\n*.tfvars\n!terraform.tfvars.example" > .gitignore
  echo -e "  ${GREEN}CREATED${NC}  .gitignore with common exclusions"
fi

# ---- Step 5: Preflight check ----
echo ""
echo -e "${BOLD}[5/5] Preflight check${NC}"
echo ""

# Find the preflight script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFLIGHT="${SCRIPT_DIR}/resources/session0-preflight.sh"

if [ -f "$PREFLIGHT" ]; then
  bash "$PREFLIGHT"
else
  # Maybe we're running from the capstone repo, not the curriculum repo
  echo -e "  ${YELLOW}SKIP${NC}  Preflight script not found at ${PREFLIGHT}"
  echo "  Run it manually from the learn-ai repo:"
  echo "  bash tracks/data-engineering/resources/session0-preflight.sh"
fi

echo ""
echo -e "${BOLD}Setup complete.${NC}"
echo ""
echo "Next steps:"
echo "  1. Activate your virtualenv: source ${VENV_DIR}/bin/activate"
echo "  2. Start Session 0 pre-work"
echo "  3. Run your baseline challenge"
echo ""
